### ISSUE TITLE
Connectin refused

### ISSUE THREAD

**Issue by xultz** [ruimarinho/docker-openvpn-monitor#1]
Hello!

I installed openvpn and openvpn-monitor docker container in an Ubuntu 18.04 server. I configured openvpn to open the management service on port 5555, and I checked with telnet that it is open and working fine (I sent commands, and I saw on the openvpn that it got a connection).
I disconnected the telnet, and when I run the docker with the command "docker run --name openvpn-monitor -e OPENVPNMONITOR_SITES_0_ALIAS=UDP -e OPENVPNMONITOR_SITES_0_HOST=127.0.0.1 -e OPENVPNMONITOR_SITES_0_NAME=UDP -e OPENVPNMONITOR_SITES_0_PORT=5555 -p 80:80 ruimarinho/openvpn-monitor", I see no activities on the openvpn log, and when I open the openvpn-monitor page, it shows the message "Could not connect to 127.0.0.1:5555 (Connection refused)"

What am I doing wrong? Are there any log where I could check what's going on? Are there any configuration file I should change?

Thank you for any help!

**Comment by ruimarinho** [comment]
You need to point the host the correct container IP/hostname, not the localhost one.
