### ISSUE TITLE
Unable to start on Raspberry Pi 4

### ISSUE THREAD

**Issue by hmehra** [ruimarinho/docker-openvpn-monitor#13]
When I tried to run the container on my RPi 4, confd gave this error -

```
docker run --name openvpn-monitor -p 10000:80 ruimarinho/openvpn-monitor
/usr/bin/confd: line 1: syntax error: unexpected word (expecting ")")

```
Since this is now supported on arm32v7, is this expected?

**Comment by MoweME** [comment]
Same problem over here!

**Comment by ruimarinho** [comment]
I think Raspberry Pi 4 is actually arm64, but I think I've spotted the issue and will try to push an updated version tomorrow. Sorry about that!

**Comment by ruimarinho** [comment]
@hmehra @MoweME could you give it a try now please?

**Comment by hmehra** [comment]
@ruimarinho  Working fine now. Thanks for the fix.
