### ISSUE TITLE
Info not displaying correctly

### ISSUE THREAD

**Issue by popeyesfx** [ruimarinho/docker-openvpn-monitor#17]
![Screenshot 2020-11-17 at 10 04 54](https://user-images.githubusercontent.com/18743946/99376211-8a0cf600-28bc-11eb-9fa3-ce71421d6e64.png)

The screen does not display correctly. As this is a container I am not sure where the issue is. I am using Safari on a Mac running Big Sur to access the web portal. The container is running on a raspberry pi as is the VPN

**Comment by ruimarinho** [comment]
Hi @popeyesfx. Could you take a look at your console? Stylesheets seems to be missing, but they're working fine here. Maybe some content blocker on your client?

**Comment by popeyesfx** [comment]
Hi
I am not sure what you mean style sheets missing, I do not have anything blocked in safari, are there seperate sheets needed
