### ISSUE TITLE
Users Displaying Undefined

### ISSUE THREAD

**Issue by heltonengc** [ruimarinho/docker-openvpn-monitor#18]
Congratulations for this project! It helped me a lot to control my users. However, several times, connected users are being shown as undefined. This happens when it exceeds a certain number of connected users. I'll send a picture!

![image](https://user-images.githubusercontent.com/19825166/100111158-9230dc80-2e4c-11eb-8f33-2a0a23ce0549.png)

**Comment by ruimarinho** [comment]
@heltonengc this should be getting extracted from the certificate CN. If you don't mind, I'd suggest directing this query upstream instead (https://github.com/furlongm/openvpn-monitor). Thanks!
