### ISSUE TITLE
Could not connect to openvpn:5555 (Temporary failure in name resolution)

### ISSUE THREAD

**Issue by clerrific** [ruimarinho/docker-openvpn-monitor#23]
Hello.

I would like to seek assistance from you guys. It was not running perfectly and this is the first time I encountered this error.

Can you help me on our issue please.
![2021-04-28_06h32_57](https://user-images.githubusercontent.com/17025388/116320884-a5751900-a7eb-11eb-877d-aaa582426bf8.png)

I also checked its docker openvpn-monitor logs
![image](https://user-images.githubusercontent.com/17025388/116320997-dead8900-a7eb-11eb-9f30-ac930df79c44.png)

Here is my configuration in docker-compose yaml file
![image](https://user-images.githubusercontent.com/17025388/116321059-fb49c100-a7eb-11eb-87aa-29b56eedeca5.png)

Here is my openvpn configuration file. I already input the 0.0.0.0 5555 but still the same
![image](https://user-images.githubusercontent.com/17025388/116321563-d99d0980-a7ec-11eb-9c5e-260d0a325124.png)

Then I tried your other version but still the same
![image](https://user-images.githubusercontent.com/17025388/116321199-30eeaa00-a7ec-11eb-8d0d-8bcdd505d50f.png)

**Comment by m0rtalis** [comment]
> It was not running perfectly and this is the first time I encountered this error.
I assume you mean it was running perfectly?

The issue seems to be, that the container `openvpn_monitor` cannot resolve the hostname 'srv-dr-openvpn'.
Try it with `docker-compose run openvpn_monitor `
To fix it either use `openvpn` in the env-variable `OPENVPNMONITOR_SITES_0_NAME`, docker will automatically resolve it for you to the openvpn container or use [links](https://docs.docker.com/compose/networking/#links). For that add to the `openvpn_monitor` service:

    openvpn_monitor:
    [...]
        links:
            - "openvpn:svr-dr-openvpn"

**Comment by clerrific** [comment]
Hello @m0rtalis 

Thank you from your response. 

I modified my docker-compose yaml file. 
![image](https://user-images.githubusercontent.com/17025388/117563425-5925b500-b0d8-11eb-95e6-b64ec8199ff0.png)

But shows the same error 
![image](https://user-images.githubusercontent.com/17025388/117563460-98ec9c80-b0d8-11eb-9b44-3a027bd33758.png)

Do I need to change my hostname and remove the dr in hostname. It will be like svr-openvpn ? 

I cannot perform a restart for changing hostname since it is used in our production environment

**Comment by ruimarinho** [comment]
@clerrific enter the openvpn-monitor container (`docker exec -it <containerId/name> sh`) and then do a `cat /etc/hosts`. Try pinging the linked container to see if you have connectivity.
