### ISSUE TITLE
CORS Issue when using the latest image

### ISSUE THREAD

**Issue by fotisp** [ruimarinho/docker-openvpn-monitor#24]
Hello,

I just pulled the latest version of the docker images, and styling seems to be broken due to the fact that static assets are failing due to CORS.

![Screenshot 2021-04-30 at 3 34 52 PM](https://user-images.githubusercontent.com/210779/116696259-589b6900-a9ca-11eb-8735-920d669a601d.png)

I am proxying this over Apache, but it shouldn't cause a problem.

[Edit] - This seems to be happening only on Safari
Version 14.0.3 (16610.4.3.1.7)

**Comment by ruimarinho** [comment]
Your origin`monitoring.existanze.lan` seems to be disallowing those requests. Seems to be an issue with your virtual host configuration within Apache. Might be useful to post the response headers you're seeing.

**Comment by fotisp** [comment]
Hello @ruimarinho this is only on Safari, on Chrome it works fine. So it is not a headers issue on the proxy.

**Comment by ruimarinho** [comment]
Could be related to HTTP vs HTTPS.
