### ISSUE TITLE
can webpage be password protected ?

### ISSUE THREAD

**Issue by emoxam** [ruimarinho/docker-openvpn-monitor#34]
Hi!
Because anybody can disconnects VPN connections can webpage be password protected ?
Thanks

**Comment by m0rtalis** [comment]
No, you need to provide your own authentication solution, eg. with [Traefik and Basic Auth](https://doc.traefik.io/traefik/middlewares/http/basicauth/)

**Comment by emoxam** [comment]
Maybe we can create feature request? It will be very useful!
thanks )

**Comment by m0rtalis** [comment]
I doubt it. That's out of scope for this image and has been rejected before #12

**Comment by emoxam** [comment]
Got it! Thanks!
