### ISSUE TITLE
GeoLite 404

### ISSUE THREAD

**Issue by ajerit** [ruimarinho/docker-openvpn-monitor#4]
Hello!

I tried building the Dockerfile and the GeoLite download returns an 404 error. They updated the file that the dockerfile tries to download, and now is a tar.gz file

https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

What can I do to make it work again?

Thank you!

**Comment by ruimarinho** [comment]
Fixed by https://github.com/ruimarinho/docker-openvpn-monitor/commit/161708f051321d820e66d85767e0e7893a405997.
