### ISSUE TITLE
modify title

### ISSUE THREAD

**Issue by xymsayly** [ruimarinho/docker-openvpn-monitor#6]
How should I modify the content of the title .Thanks
![image](https://user-images.githubusercontent.com/34665997/73723853-0175fc80-4765-11ea-8458-047bca0e036f.png)

**Comment by markdavidburke** [comment]
You can change 'Example' to what you want.

`-e OPENVPNMONITOR_DEFAULT_SITE=BANANANANANANAS`

**Comment by ruimarinho** [comment]
Indeed :)
