### ISSUE TITLE
show_disconnect support

### ISSUE THREAD

**Issue by nayneyT** [ruimarinho/docker-openvpn-monitor#7]
Hi,

Just raising an issue on the off-chance that you will consider adding support for the show_disconnect parameter in the openvpn-monitor.conf file.

I think that addition would add full support as per the openvpn-monitor capabilities.

Regards

**Comment by ruimarinho** [comment]
Indeed, this should have been supported since day one but the underscore messes with confd. It's now been fixed, so you just need to update your docker image to latest. Just remember to use `_SHOWDISCONNECT` instead.

Cheers!
